-- Listening Bingo: expand the built-in category pool from 175 to ~1000
-- (supabase/seed/song_bingo_categories_176_1000_append.csv, provided
-- 2026-07-08) so dealt cards overlap far less. Existing games are untouched —
-- game pools are snapshots taken at launch; new games (and the launch UI's
-- pool editor) see the full set. on conflict skips any label already seeded.

insert into public.bingo_categories (label) values
  ('Song by an artist from Africa'),
  ('Song by an artist from Asia'),
  ('Song by an artist from Europe'),
  ('Song by an artist from South America'),
  ('Song by an artist from the Caribbean'),
  ('Song by an artist from Oceania'),
  ('Song by an artist from Canada'),
  ('Song by an artist from Mexico'),
  ('Song by an artist from Brazil'),
  ('Song by an artist from Jamaica'),
  ('Song by an artist from Nigeria'),
  ('Song by an artist from South Korea'),
  ('Song by an artist from Japan'),
  ('Song by an artist from France'),
  ('Song by an artist from the UK'),
  ('Song by an artist from Ireland'),
  ('Song by an artist from Australia'),
  ('Song by an artist from New Orleans'),
  ('Song by an artist from Detroit'),
  ('Song by an artist from Atlanta'),
  ('Song by an artist from Chicago'),
  ('Song by an artist from Los Angeles'),
  ('Song by an artist from Philadelphia'),
  ('Song by an artist from Texas'),
  ('Song by an artist from the Pacific Northwest'),
  ('Song by an artist from the Midwest'),
  ('Song by an artist from the South'),
  ('Song by an artist from a small town'),
  ('Song by an artist whose name is an acronym'),
  ('Song by an artist with punctuation in their name'),
  ('Song by an artist with a food in their name'),
  ('Song by an artist with a weather word in their name'),
  ('Song by an artist with a body part in their name'),
  ('Song by an artist with a royal title in their name'),
  ('Song by an artist with a family role in their name'),
  ('Song by an artist with a month in their name'),
  ('Song by an artist with a geographic word in their name'),
  ('Song by an artist with a space-related name'),
  ('Song by an artist with a plant in their name'),
  ('Song by an artist with a profession in their name'),
  ('Song by an artist whose real name you know'),
  ('Song by an artist whose real name surprised you'),
  ('Song by an artist who produces their own music'),
  ('Song by an artist who writes for other artists'),
  ('Song by an artist who was in a reality show'),
  ('Song by an artist who was in a Disney or Nickelodeon project'),
  ('Song by an artist who was in a famous band before going solo'),
  ('Song by an artist who is better known as a producer'),
  ('Song by an artist who is better known as a songwriter'),
  ('Song by an artist who is better known as a DJ'),
  ('Song by an artist with a famous parent'),
  ('Song by an artist with a famous sibling'),
  ('Song by an artist who performs in costume or character'),
  ('Song by an artist with a masked identity'),
  ('Song by an artist who uses Auto-Tune as a signature sound'),
  ('Song by an artist known for falsetto'),
  ('Song by an artist known for whispery vocals'),
  ('Song by an artist known for raspy vocals'),
  ('Song by an artist known for screaming vocals'),
  ('Song by an artist known for talk-singing'),
  ('Song by an artist whose voice you recognized immediately'),
  ('Song by an artist you could not identify by voice alone'),
  ('Song by an artist who died young'),
  ('Song by an artist who released music posthumously'),
  ('Song by an artist who had a major comeback after 10+ years'),
  ('Song by an artist who disappeared from the mainstream'),
  ('Song by an artist who was part of a famous feud'),
  ('Song by an artist with a cult fanbase'),
  ('Song by an artist you discovered through another artist'),
  ('Song by an artist with a tiny discography'),
  ('Song by an artist with a massive discography'),
  ('Song by an artist who has released music in multiple languages'),
  ('Song by an artist who switched genres'),
  ('Song by an artist who started as a rapper and later sang'),
  ('Song by an artist who started as a singer and later rapped'),
  ('Song by an artist who has a side project'),
  ('Song by a band with no original members left'),
  ('Song by a band named after a place'),
  ('Song by a band named after a book or movie'),
  ('Song by a band with an intentionally misspelled name'),
  ('Song with the word ''rain'' in the title'),
  ('Song with the word ''fire'' in the title'),
  ('Song with the word ''moon'' in the title'),
  ('Song with the word ''sun'' in the title'),
  ('Song with the word ''star'' in the title'),
  ('Song with the word ''heart'' in the title'),
  ('Song with the word ''love'' in the title'),
  ('Song with the word ''hate'' in the title'),
  ('Song with the word ''baby'' in the title'),
  ('Song with the word ''night'' in the title'),
  ('Song with the word ''morning'' in the title'),
  ('Song with the word ''home'' in the title'),
  ('Song with the word ''road'' in the title'),
  ('Song with the word ''street'' in the title'),
  ('Song with the word ''river'' in the title'),
  ('Song with the word ''ocean'' in the title'),
  ('Song with the word ''mountain'' in the title'),
  ('Song with the word ''car'' in the title'),
  ('Song with the word ''train'' in the title'),
  ('Song with the word ''plane'' in the title'),
  ('Song with the word ''phone'' in the title'),
  ('Song with the word ''radio'' in the title'),
  ('Song with the word ''money'' in the title'),
  ('Song with the word ''gold'' in the title'),
  ('Song with the word ''blue'' in the title'),
  ('Song with the word ''red'' in the title'),
  ('Song with the word ''black'' in the title'),
  ('Song with the word ''white'' in the title'),
  ('Song with the word ''green'' in the title'),
  ('Song with the word ''pink'' in the title'),
  ('Song with the word ''purple'' in the title'),
  ('Song with the word ''silver'' in the title'),
  ('Song with the word ''diamond'' in the title'),
  ('Song with the word ''king'' in the title'),
  ('Song with the word ''queen'' in the title'),
  ('Song with the word ''angel'' in the title'),
  ('Song with the word ''devil'' in the title'),
  ('Song with the word ''heaven'' in the title'),
  ('Song with the word ''hell'' in the title'),
  ('Song with the word ''ghost'' in the title'),
  ('Song with the word ''dream'' in the title'),
  ('Song with the word ''memory'' in the title'),
  ('Song with the word ''time'' in the title'),
  ('Song with the word ''forever'' in the title'),
  ('Song with the word ''today'' in the title'),
  ('Song with the word ''tomorrow'' in the title'),
  ('Song with the word ''yesterday'' in the title'),
  ('Song with the word ''alone'' in the title'),
  ('Song with the word ''together'' in the title'),
  ('Song with the word ''dance'' in the title'),
  ('Song with the word ''party'' in the title'),
  ('Song with the word ''tears'' in the title'),
  ('Song with the word ''smile'' in the title'),
  ('Song with the word ''eyes'' in the title'),
  ('Song with the word ''hands'' in the title'),
  ('Song with the word ''body'' in the title'),
  ('Song with the word ''blood'' in the title'),
  ('Song with the word ''bones'' in the title'),
  ('Song with the word ''city'' in the title'),
  ('Song with the word ''hotel'' in the title'),
  ('Song with the word ''room'' in the title'),
  ('Song with the word ''door'' in the title'),
  ('Song with the word ''window'' in the title'),
  ('Song with the word ''light'' in the title'),
  ('Song with the word ''shadow'' in the title'),
  ('Song with the word ''smoke'' in the title'),
  ('Song with the word ''fireworks'' in the title'),
  ('Song with the word ''coffee'' in the title'),
  ('Song with the word ''whiskey'' in the title'),
  ('Song with the word ''beer'' in the title'),
  ('Song with the word ''champagne'' in the title'),
  ('Song with the word ''roses'' in the title'),
  ('Song with the word ''flowers'' in the title'),
  ('Song with the word ''summer'' in the title'),
  ('Song with the word ''winter'' in the title'),
  ('Song with the word ''spring'' in the title'),
  ('Song with the word ''fall'' in the title'),
  ('Song with the word ''Sunday'' in the title'),
  ('Song with the word ''Monday'' in the title'),
  ('Song with the word ''Friday'' in the title'),
  ('Song with the word ''midnight'' in the title'),
  ('Song with the word ''noon'' in the title'),
  ('Song with the word ''highway'' in the title'),
  ('Song with the word ''taxi'' in the title'),
  ('Song with the word ''subway'' in the title'),
  ('Song with the word ''island'' in the title'),
  ('Song with the word ''planet'' in the title'),
  ('Song with the word ''space'' in the title'),
  ('Song with the word ''monster'' in the title'),
  ('Song with the word ''magic'' in the title'),
  ('Song with the word ''church'' in the title'),
  ('Song with the word ''school'' in the title'),
  ('Song with the word ''work'' in the title'),
  ('Song with the word ''boss'' in the title'),
  ('Song with the word ''doctor'' in the title'),
  ('Song with the word ''rich'' in the title'),
  ('Song with the word ''poor'' in the title'),
  ('Song with the word ''famous'' in the title'),
  ('Song with the word ''lonely'' in the title'),
  ('Song with the word ''wild'' in the title'),
  ('Song with the word ''sweet'' in the title'),
  ('Song with the word ''dirty'' in the title'),
  ('Song with the word ''clean'' in the title'),
  ('Song with the word ''slow'' in the title'),
  ('Song with the word ''fast'' in the title'),
  ('Song with the word ''loud'' in the title'),
  ('Song with the word ''quiet'' in the title'),
  ('Song with the word ''broken'' in the title'),
  ('Song with the word ''golden'' in the title'),
  ('Song with the word ''electric'' in the title'),
  ('Song with the word ''digital'' in the title'),
  ('Song with the word ''analog'' in the title'),
  ('Song with the word ''record'' in the title'),
  ('Song with the word ''needle'' in the title'),
  ('Song with the word ''groove'' in the title'),
  ('Song with the word ''song'' in the title'),
  ('Song with the word ''music'' in the title'),
  ('Song with the word ''letter'' in the title'),
  ('Song with the word ''kiss'' in the title'),
  ('Song with the word ''shoes'' in the title'),
  ('Song with the word ''jacket'' in the title'),
  ('Song with the word ''mirror'' in the title'),
  ('Song with the word ''camera'' in the title'),
  ('Song with the word ''picture'' in the title'),
  ('Song with the word ''movie'' in the title'),
  ('Song with the word ''game'' in the title'),
  ('Song with the word ''war'' in the title'),
  ('Song with the word ''peace'' in the title'),
  ('Song with the word ''homecoming'' in the title'),
  ('Song with the word ''birthday'' in the title'),
  ('Song that includes a phone call'),
  ('Song that includes a text message'),
  ('Song that includes a voicemail'),
  ('Song that includes a letter'),
  ('Song that includes a name being repeated'),
  ('Song that includes a color being repeated'),
  ('Song that includes a city being named'),
  ('Song that includes a brand name'),
  ('Song that includes a car model'),
  ('Song that includes a luxury item'),
  ('Song that includes a food order'),
  ('Song that includes a drink order'),
  ('Song that includes a prayer'),
  ('Song that includes a curse word in the chorus'),
  ('Song that includes a countdown'),
  ('Song that includes a spoken intro'),
  ('Song that includes a spoken outro'),
  ('Song that includes laughter'),
  ('Song that includes crying'),
  ('Song that includes a doorbell'),
  ('Song that includes sirens'),
  ('Song that includes crowd noise'),
  ('Song that includes rain sounds'),
  ('Song that includes ocean sounds'),
  ('Song that includes bird sounds'),
  ('Song that includes a dog barking'),
  ('Song that includes a train sound'),
  ('Song that includes a radio DJ'),
  ('Song that includes a fake news report'),
  ('Song that includes a sampled interview'),
  ('Song with a flute part'),
  ('Song with a clarinet part'),
  ('Song with an oboe part'),
  ('Song with a trumpet solo'),
  ('Song with a trombone part'),
  ('Song with a tuba or sousaphone part'),
  ('Song with a violin lead'),
  ('Song with cello as a main texture'),
  ('Song with a harp part'),
  ('Song with a banjo part'),
  ('Song with mandolin'),
  ('Song with sitar'),
  ('Song with tabla'),
  ('Song with congas'),
  ('Song with bongos'),
  ('Song with cowbell'),
  ('Song with maracas'),
  ('Song with castanets'),
  ('Song with a xylophone or marimba part'),
  ('Song with glockenspiel'),
  ('Song with a pipe organ'),
  ('Song with a church organ'),
  ('Song with a synth lead'),
  ('Song with a vocoder'),
  ('Song with a talk box'),
  ('Song with a drum machine you can clearly hear'),
  ('Song with 808 cowbell'),
  ('Song with a booming 808 bass'),
  ('Song with a walking bassline'),
  ('Song with slap bass'),
  ('Song with a distorted bassline'),
  ('Song with fingerpicked guitar'),
  ('Song with acoustic guitar as the main instrument'),
  ('Song with distorted electric guitar'),
  ('Song with a clean electric guitar riff'),
  ('Song with a piano ballad intro'),
  ('Song with Rhodes or Wurlitzer keys'),
  ('Song with a string quartet feel'),
  ('Song with orchestral swells'),
  ('Song with a marching band feel'),
  ('Song with a brass band feel'),
  ('Song with a gospel choir ending'),
  ('Song with layered harmonies'),
  ('Song with call-and-response vocals'),
  ('Song with a duet section'),
  ('Song with a group chant'),
  ('Song with crowd singalong energy'),
  ('Song with a false ending'),
  ('Song with a hidden track feel'),
  ('Song with a cold open'),
  ('Song that starts with the chorus'),
  ('Song that never repeats a chorus'),
  ('Song with a bridge that steals the show'),
  ('Song with a post-chorus hook'),
  ('Song with a pre-chorus better than the chorus'),
  ('Song with a breakdown section'),
  ('Song with a drop'),
  ('Song with no chorus'),
  ('Song with no bridge'),
  ('Song with a tempo change'),
  ('Song with a time signature that feels unusual'),
  ('Song in waltz time'),
  ('Song built around a loop'),
  ('Song built around one chord'),
  ('Song that changes genres halfway through'),
  ('Song that starts quiet and ends huge'),
  ('Song that starts huge and strips down'),
  ('Song with intentionally lo-fi production'),
  ('Song with very polished production'),
  ('Song with bedroom-pop production'),
  ('Song with a live-band feel'),
  ('Song with a demo-like feel'),
  ('Song with a cassette tape texture'),
  ('Song with vinyl crackle'),
  ('Song with a reversed sound effect'),
  ('Song with a record scratch'),
  ('Song with a DJ tag'),
  ('Song with producer tags'),
  ('Song with chopped-and-screwed vocals'),
  ('Song with pitched-up vocals'),
  ('Song with pitched-down vocals'),
  ('Song with layered ad-libs'),
  ('Song where the ad-libs are the best part'),
  ('Song where the drums carry it'),
  ('Song where the melody carries it'),
  ('Song where the lyrics carry it'),
  ('Song where the production carries it'),
  ('Song where silence or space is a major part'),
  ('Song with a very busy arrangement'),
  ('Song with a minimalist arrangement'),
  ('Song that sounds expensive'),
  ('Song that sounds intentionally cheap'),
  ('Song that sounds like it was recorded in a room'),
  ('Song that sounds like it was recorded in a stadium'),
  ('Song that sounds like a voicemail'),
  ('Song that sounds like a lullaby'),
  ('Song that sounds like a marching song'),
  ('Song that sounds like a chant'),
  ('Song that sounds underwater'),
  ('Song that sounds futuristic'),
  ('Song that sounds dusty'),
  ('Song that sounds sunny'),
  ('Song that sounds nocturnal'),
  ('Song with a perfect opening 10 seconds'),
  ('Song with a perfect final 10 seconds'),
  ('Song with a transition into the next track'),
  ('Song that works best with headphones'),
  ('Song that works best in a car'),
  ('Song that works best on speakers'),
  ('Song that would be ruined by bad speakers'),
  ('Song that has a feature but no credited feature'),
  ('Song where the feature steals the song'),
  ('Song where the hook is sung by someone else'),
  ('Song with a sample you recognized immediately'),
  ('Song with a sample you had to look up'),
  ('Song with interpolation rather than a direct sample'),
  ('Dancehall song'),
  ('Dub song'),
  ('Roots reggae song'),
  ('Lovers rock song'),
  ('Soca song'),
  ('Kompa song'),
  ('Zouk song'),
  ('Bossa nova song'),
  ('Samba song'),
  ('MPB song'),
  ('Tango song'),
  ('Flamenco song'),
  ('Fado song'),
  ('Highlife song'),
  ('Afrobeat song'),
  ('Afropop song'),
  ('Rai song'),
  ('Qawwali song'),
  ('Bollywood song'),
  ('Punjabi pop song'),
  ('Desi hip-hop song'),
  ('Arabic pop song'),
  ('Turkish psych-rock song'),
  ('Anatolian rock song'),
  ('Cantopop song'),
  ('Mandopop song'),
  ('Thai pop song'),
  ('Vietnamese pop song'),
  ('P-pop song'),
  ('K-indie song'),
  ('City pop song'),
  ('Vaporwave song'),
  ('Future funk song'),
  ('Chillwave song'),
  ('Trip-hop song'),
  ('Downtempo song'),
  ('UK garage song'),
  ('2-step garage song'),
  ('Jungle song'),
  ('Breakbeat song'),
  ('Trance song'),
  ('Eurodance song'),
  ('Italo disco song'),
  ('Hi-NRG song'),
  ('Electroclash song'),
  ('Post-punk song'),
  ('Art rock song'),
  ('Math rock song'),
  ('Post-rock song'),
  ('Prog rock song'),
  ('Glam rock song'),
  ('Garage rock song'),
  ('Surf rock song'),
  ('Rockabilly song'),
  ('Psychobilly song'),
  ('Hardcore punk song'),
  ('Pop punk song'),
  ('Riot grrrl song'),
  ('Goth song'),
  ('Darkwave song'),
  ('Dream pop song'),
  ('Slowcore song'),
  ('Noise rock song'),
  ('Power pop song'),
  ('Britpop song'),
  ('Madchester song'),
  ('Southern rock song'),
  ('Heartland rock song'),
  ('Alt-country song'),
  ('Outlaw country song'),
  ('Country pop song'),
  ('Honky-tonk song'),
  ('Americana song'),
  ('Singer-songwriter song'),
  ('Chamber pop song'),
  ('Baroque pop song'),
  ('Indie sleaze song'),
  ('Bloghouse song'),
  ('Crunk song'),
  ('Snap rap song'),
  ('Hyphy song'),
  ('Drill song'),
  ('UK drill song'),
  ('Grime song'),
  ('G-funk song'),
  ('Miami bass song'),
  ('Phonk song'),
  ('Cloud rap song'),
  ('Conscious rap song'),
  ('Horrorcore song'),
  ('Neo-soul song'),
  ('Quiet storm song'),
  ('New jack swing song'),
  ('Contemporary R&B song'),
  ('Alternative R&B song'),
  ('Freestyle song'),
  ('Latin trap song'),
  ('Corridos tumbados song'),
  ('Norteño song'),
  ('Mariachi song'),
  ('Tejano song'),
  ('Ranchera song'),
  ('Kuduro song'),
  ('Baile funk song'),
  ('Jersey club song'),
  ('Baltimore club song'),
  ('Song that hit #1 on Billboard Hot 100'),
  ('Song that never charted but became beloved'),
  ('Song that became popular years after release'),
  ('Song that was a TikTok trend'),
  ('Song from a movie trailer'),
  ('Song from a commercial'),
  ('Song from a sports video game soundtrack'),
  ('Song from a Tony Hawk game soundtrack'),
  ('Song from a FIFA/EA FC soundtrack'),
  ('Song from a Grand Theft Auto radio station'),
  ('Song from an anime opening'),
  ('Song from an anime ending'),
  ('Song from a Disney movie'),
  ('Song from a non-Disney animated movie'),
  ('Song from a horror movie soundtrack'),
  ('Song from a rom-com soundtrack'),
  ('Song from a teen movie soundtrack'),
  ('Song from a prestige TV drama'),
  ('Song from a reality TV moment'),
  ('Song from a viral internet video'),
  ('Song from a meme'),
  ('Song from a protest movement'),
  ('Song associated with a dance craze'),
  ('Song associated with a specific holiday'),
  ('Song associated with Christmas but not explicitly Christmas'),
  ('Song associated with Halloween'),
  ('Song played at sporting events'),
  ('Song often used as walk-up music'),
  ('Song often played at weddings'),
  ('Song often played at karaoke'),
  ('Song you would hear at a dive bar'),
  ('Song you would hear at a club'),
  ('Song you would hear at a coffee shop'),
  ('Song you would hear in an elevator'),
  ('Song that feels like mall music'),
  ('Song that feels like a department store in December'),
  ('Song that feels like a college party'),
  ('Song that feels like a middle school dance'),
  ('Song that feels like a high school prom'),
  ('Song that feels like a graduation montage'),
  ('Song from the first album you ever bought'),
  ('Song from the first artist you remember loving'),
  ('Song from a playlist you made years ago'),
  ('Song from an album with iconic cover art'),
  ('Song from an album with a terrible cover'),
  ('Song from an album with no skips according to fans'),
  ('Song from a critically hated album'),
  ('Song from a critically beloved album'),
  ('Song from an album that won Album of the Year'),
  ('Song from an album that lost Album of the Year'),
  ('Song from an album released on your birthday'),
  ('Song released in the month you were born'),
  ('Song released during your high school years'),
  ('Song released during your college years'),
  ('Song released before 1950'),
  ('Song from the 1940s or earlier'),
  ('Song released exactly 10 years ago'),
  ('Song released exactly 20 years ago'),
  ('Song released exactly 30 years ago'),
  ('Song from an artist''s sophomore album'),
  ('Song from an artist''s third album'),
  ('Song from an artist''s most recent album'),
  ('Song from an artist''s most streamed album'),
  ('Song from an album with a title track'),
  ('Song that is the title track of an album'),
  ('Song that was a B-side'),
  ('Song released as a standalone single'),
  ('Song released after the album became popular'),
  ('Song that was leaked before release'),
  ('Song from a surprise drop'),
  ('Song from a concept album'),
  ('Song from a double album'),
  ('Song from an EP'),
  ('Song from a mixtape'),
  ('Song from an unplugged session'),
  ('Song from a Tiny Desk performance'),
  ('Song from a live performance video'),
  ('Song from a remix album'),
  ('Song from a charity single'),
  ('Song made for a movie but bigger than the movie'),
  ('Song that won an Oscar'),
  ('Song that was nominated for an Oscar'),
  ('Song that won Eurovision'),
  ('Song from a Eurovision contestant'),
  ('Song for cooking dinner'),
  ('Song for cleaning your apartment'),
  ('Song for walking over a bridge'),
  ('Song for taking the subway at night'),
  ('Song for a rainy commute'),
  ('Song for a sunny morning walk'),
  ('Song for a late-night Uber'),
  ('Song for driving with the windows down'),
  ('Song for staring out a train window'),
  ('Song for getting ready to go out'),
  ('Song for leaving the party early'),
  ('Song for the last song at a party'),
  ('Song for a first date'),
  ('Song for getting ghosted'),
  ('Song for texting someone you should not text'),
  ('Song for deleting someone''s number'),
  ('Song for moving into a new apartment'),
  ('Song for leaving your hometown'),
  ('Song for returning to your hometown'),
  ('Song for a beach sunset'),
  ('Song for a rooftop hang'),
  ('Song for a backyard barbecue'),
  ('Song for a dinner party'),
  ('Song for a pregame'),
  ('Song for a postgame'),
  ('Song for a hangover morning'),
  ('Song for making coffee'),
  ('Song for staying in on a Friday'),
  ('Song for walking home alone'),
  ('Song for main character energy'),
  ('Song for side character energy'),
  ('Song for underdog energy'),
  ('Song for villain monologue energy'),
  ('Song for a training montage'),
  ('Song for a breakup montage'),
  ('Song for a reunion montage'),
  ('Song for a road trip montage'),
  ('Song for a heist scene'),
  ('Song for a chase scene'),
  ('Song for a slow dance scene'),
  ('Song for a bar fight scene'),
  ('Song for a coming-of-age movie ending'),
  ('Song for the opening credits of your life'),
  ('Song for the closing credits of your life'),
  ('Song for a dramatic entrance'),
  ('Song for a dramatic exit'),
  ('Song for a quiet win'),
  ('Song for a petty win'),
  ('Song for losing gracefully'),
  ('Song for losing badly'),
  ('Song for being delusional'),
  ('Song for feeling too confident'),
  ('Song for pretending you are fine'),
  ('Song for admitting you are not fine'),
  ('Song for a Sunday reset'),
  ('Song for Monday motivation'),
  ('Song for Wednesday survival'),
  ('Song for Friday freedom'),
  ('Song for Saturday chaos'),
  ('Song for a snow day'),
  ('Song for a heat wave'),
  ('Song for the first warm day of the year'),
  ('Song for the first cold day of the year'),
  ('Song for golden hour'),
  ('Song for blue hour'),
  ('Song for 3 AM'),
  ('Song for sunrise'),
  ('Song for sunset'),
  ('Song for midnight'),
  ('Song for a museum walk'),
  ('Song for a thrift store trip'),
  ('Song for a record store browse'),
  ('Song for a bookstore browse'),
  ('Song for a grocery store run'),
  ('Song for folding laundry'),
  ('Song for packing a suitcase'),
  ('Song for unpacking after a trip'),
  ('Song for waiting at an airport'),
  ('Song for landing in a new city'),
  ('Song for walking into a fancy hotel'),
  ('Song for eating pizza at 2 AM'),
  ('Song for a diner booth'),
  ('Song for a dive bar jukebox'),
  ('Song for a hotel lobby'),
  ('Song for a casino floor'),
  ('Song for a wedding afterparty'),
  ('Song for a family party'),
  ('Song for a cousin''s playlist'),
  ('Song for impressing someone with your taste'),
  ('Song for annoying the whole group'),
  ('Song for clearing the aux cord'),
  ('Song for saving the aux cord'),
  ('Song for the perfect 15-minute walk'),
  ('Song for a 5-minute errand'),
  ('Song for a workout warmup'),
  ('Song for the last rep'),
  ('Song for a cooldown'),
  ('Song for a long shower'),
  ('Song for a short attention span'),
  ('Song for reading on a train'),
  ('Song for journaling'),
  ('Song for doomscrolling'),
  ('Song for deleting social media'),
  ('Song for feeling nostalgic about something that never happened'),
  ('Song for a fake relationship in your head'),
  ('Song for a crush you barely know'),
  ('Song for an ex you are over but not really'),
  ('Song for a friend breakup'),
  ('Song for making a bad decision'),
  ('Song for making the right decision'),
  ('Song for taking yourself too seriously'),
  ('Song for not taking anything seriously'),
  ('Song for a tiny apartment party'),
  ('Song for a massive festival crowd'),
  ('Song for a candlelit room'),
  ('Song for a neon-lit room'),
  ('Song for a parking lot conversation'),
  ('Song for a long voicemail'),
  ('Song for when the group chat is dead'),
  ('Song for when the group chat is on fire'),
  ('Song for someone with expensive taste'),
  ('Song for someone with chaotic taste'),
  ('Song for someone who says they listen to everything'),
  ('Song for someone who only listens to hits'),
  ('Song found by searching a random city name'),
  ('Song found by searching a random color'),
  ('Song found by searching a random emotion'),
  ('Song found by searching a random food'),
  ('Song found by searching a random month'),
  ('Song found by searching a random animal'),
  ('Song found from an artist''s related artists page'),
  ('Song found from a playlist made by a stranger'),
  ('Song found from a playlist with under 100 saves'),
  ('Song found from a friend''s public playlist'),
  ('Song found from a radio station algorithm'),
  ('Song found from a record label''s page'),
  ('Song found from an artist''s first release'),
  ('Song found from an artist''s least popular album'),
  ('Song found from an album''s final track'),
  ('Song found from a producer credit'),
  ('Song found from a songwriter credit'),
  ('Song found from a background vocalist credit'),
  ('Song found from a featured artist rabbit hole'),
  ('Song found from a cover version rabbit hole'),
  ('Song found from a sample chain'),
  ('Song found from a music subreddit'),
  ('Song found from a music blog'),
  ('Song found from an old Pitchfork review'),
  ('Song found from a YouTube comment'),
  ('Song found from a live performance clip'),
  ('Song found from a Tiny Desk rabbit hole'),
  ('Song found from a festival lineup'),
  ('Song found from a local venue calendar'),
  ('Song found from a movie end credits list'),
  ('Song found from Shazam or sound recognition'),
  ('Song you picked only because of the cover art'),
  ('Song you picked only because of the title'),
  ('Song you picked only because of the artist name'),
  ('Song you picked because the album cover was ugly'),
  ('Song you picked because the runtime was weird'),
  ('Song you picked without previewing it'),
  ('Song you picked from page 2 or deeper of search results'),
  ('Song you picked by scrolling to a random year'),
  ('Song by the least famous artist you can find'),
  ('Song from an artist with no Wikipedia page'),
  ('Song from an album with fewer than 10 ratings online'),
  ('Song from a local band in your city'),
  ('Song from a local band in a city you have visited'),
  ('Song from a city you want to visit'),
  ('Song from a country whose language you cannot identify'),
  ('Song from a genre you had to Google'),
  ('Song from a subgenre you had never heard of'),
  ('Song with an instrument you had to Google'),
  ('Song with a title you had to translate'),
  ('Song where you cannot pronounce the artist name'),
  ('Song where you cannot pronounce the title'),
  ('Song you would never have clicked without bingo'),
  ('Song that was better than expected'),
  ('Song that was worse than expected'),
  ('Song that made you want to hear the album'),
  ('Song that made you never want to hear the album'),
  ('Song you would send to one specific club member'),
  ('Song you would not play around your parents'),
  ('Song you would play around your parents to confuse them'),
  ('Song from an artist with exactly one album'),
  ('Song from an artist with no profile photo'),
  ('Song from an album released independently'),
  ('Song from a label you recognize'),
  ('Song from a label you have never heard of'),
  ('Song from a compilation album'),
  ('Song from a tribute album'),
  ('Song from a benefit album'),
  ('Song from a regional scene compilation'),
  ('Song from a DJ mix tracklist'),
  ('Song from a playlist with a ridiculous name'),
  ('Song from a playlist with a very boring name'),
  ('Song from a playlist made by Spotify/Apple editors'),
  ('Song from a playlist not made by a streaming service'),
  ('Song from the last page of an artist''s discography'),
  ('Song from the middle of an album you would normally skip'),
  ('Song from an artist you only know from one song'),
  ('Song from an artist you confused with another artist'),
  ('Song by someone who opened for a bigger act'),
  ('Song by someone who featured on a song you already like'),
  ('Song by an artist with a monthly listener count under 10k'),
  ('Song by an artist with a monthly listener count between 10k and 100k'),
  ('Song by an artist with a monthly listener count between 1M and 5M'),
  ('Song with no obvious genre label'),
  ('Song that sounds like two genres at once'),
  ('Song that sounds nothing like its cover art'),
  ('Song whose title made you laugh'),
  ('Song whose title made you nervous'),
  ('Song whose first 5 seconds hooked you'),
  ('Song whose first 5 seconds almost lost you'),
  ('Song you would give a second chance after one listen'),
  ('Song you are shocked you had never heard before'),
  ('Opening track from an album'),
  ('Second track from an album'),
  ('Third track from an album'),
  ('Track 4 from an album'),
  ('Track 5 from an album'),
  ('Track 6 from an album'),
  ('Track 7 from an album'),
  ('Track 8 from an album'),
  ('Track 9 from an album'),
  ('Track 10 from an album'),
  ('Final track from an album'),
  ('Penultimate track from an album'),
  ('Middle track from an album'),
  ('Shortest song on an album'),
  ('Longest song on an album'),
  ('Least-streamed song on an album'),
  ('Most-streamed song on an album'),
  ('A non-single from a famous album'),
  ('A deep cut from an artist you like'),
  ('A deep cut from an artist you do not know'),
  ('A song that should have been a single'),
  ('A single that sounds like an album cut'),
  ('A skit-adjacent track'),
  ('An interlude that is actually good'),
  ('An intro track that is actually a full song'),
  ('An outro track that is actually a full song'),
  ('A song that follows the biggest hit on an album'),
  ('A song before the biggest hit on an album'),
  ('A song with the same title as the album'),
  ('A song that shares a title with another famous song'),
  ('A song that appears on multiple versions of an album'),
  ('A song added on a deluxe edition'),
  ('A song removed from a later version of an album'),
  ('A bonus track better than the main album tracks'),
  ('A remix that became more famous than the original'),
  ('A remix that should not exist'),
  ('A live version better than the studio version'),
  ('A studio version better than the live version'),
  ('An acoustic version of a non-acoustic song'),
  ('An orchestral version of a pop song'),
  ('A stripped-down version of a loud song'),
  ('A dance remix of a sad song'),
  ('A sad remix of a dance song'),
  ('A song that opens with the album title being said'),
  ('A song that ends with the album title being said'),
  ('A song that feels misplaced on its album'),
  ('A song that perfectly explains its album'),
  ('A song that could have closed the album'),
  ('A song that could have opened the album'),
  ('A song that changes how you hear the previous track'),
  ('A song that changes how you hear the next track'),
  ('A song from an album with 8 tracks or fewer'),
  ('A song from an album with 20 tracks or more'),
  ('A song from an album under 30 minutes'),
  ('A song from an album over 80 minutes'),
  ('A song from a visual album'),
  ('A song from a collaborative album'),
  ('A song from an artist''s self-titled album'),
  ('A song from an album named after a place'),
  ('A song from an album named after a person'),
  ('A song from an album with an all-caps title'),
  ('A song from an album with a lowercase title'),
  ('A song from an album with a number in the title')
on conflict (label) do nothing;
